spring:
  datasource:
    # url: jdbc:clickhouse:http://10.3.242.84:8123/sctp_test?max_query_size=100000000
    url: jdbc:clickhouse:http://localhost/wx_test?max_query_size=100000000
    username: default
    password: password
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.networkflow.backendspringboot3.controller

# 后端部署端口
server:
  port: 9600